{
  callThrowException(INTERNAL_SERVER_ERROR.getStatusCode(),"This is an exception");
}
