{
  thrown.expect(is(instanceOf(MessagingException.class)));
  thrown.expectCause(is(exception));
  Event result;
  try {
    result=just(event).transform(testProcessorThrowsException).block();
  }
 catch (  Exception e) {
    throw unwrap(e);
  }
  assertThat(result,is(nullValue()));
}
