{
  fail(exception.getMessage() + ", Root cause: " + ExceptionHelper.getRootException(exception));
}
