{
  try {
    resume(event);
  }
 catch (  MessagingException e) {
    processExceptionReplyTo(e,replyTo);
  }
}
