{
  try {
    resume(event);
  }
 catch (  Throwable e) {
    if (e instanceof MessagingException) {
      processExceptionReplyTo((MessagingException)e,replyTo);
    }
 else {
      processExceptionReplyTo(new MessagingException(event,e),replyTo);
    }
  }
}
