{
  expectedException.expectCause(is(instanceOf(ComponentException.class)));
  expectedException.expectCause(hasCause(instanceOf(ResolverException.class)));
  callAndThrowException(new ResolverException(CoreMessages.createStaticMessage("")),null);
}
