{
  if (event == null) {
    return;
  }
  Throwable e=event.getException();
  if (e == null) {
    return;
  }
  if (e.getCause() != null) {
    e=e.getCause();
  }
  logger.error("Work caused exception on '" + type + "'. Work being executed was: "+ event.getWork().toString());
  if (e instanceof Exception) {
    exceptionListener.exceptionThrown((Exception)e);
  }
 else {
    throw new MuleRuntimeException(CoreMessages.errorInvokingMessageProcessorAsynchronously(next),e);
  }
}
