{
  if (getExceptionToThrow() != null) {
    if (StringUtils.isNotBlank(exceptionText)) {
      Throwable exception=ClassUtils.instanciateClass(getExceptionToThrow(),new Object[]{exceptionText});
      throw (Exception)exception;
    }
 else {
      throw (Exception)getExceptionToThrow().newInstance();
    }
  }
 else {
    if (StringUtils.isNotBlank(exceptionText)) {
      throw new FunctionalTestException(exceptionText);
    }
 else {
      throw new FunctionalTestException();
    }
  }
}
