{
  assertThat(out,notNullValue());
  assertThat(out.getPayload(),instanceOf(ExceptionMessage.class));
  ExceptionMessage exceptionMessage=(ExceptionMessage)out.getPayload();
  Class clazz=FunctionalTestException.class;
  assertThat(exceptionMessage.getException(),either(hasCause(instanceOf(clazz))).or(hasCause(hasCause(instanceOf(clazz)))));
  assertThat(exceptionMessage.getPayload(),is("test"));
}
