{
  return (t instanceof NamingException ? ((NamingException)t).getCause() : null);
}
